import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Home from '../components/Home'

export default function Hotel() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hotel Coronado - Hotel Boutique & Resto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css?family=Mukta:400,700,800&display=swap" rel="stylesheet" />
      </Head>
      <Home />
    </div>
  )
}
